
    create table tb_category (
       id_category bigint generated by default as identity,
        nome varchar(255),
        primary key (id_category)
    );

    create table tb_lancamento (
       id_lancamento bigint generated by default as identity,
        comentario varchar(255),
        data date,
        valor double,
        id_subcategoria bigint not null,
        primary key (id_lancamento)
    );

    create table tb_subcategory (
       id_subcategory bigint generated by default as identity,
        nome varchar(255),
        category_id bigint,
        primary key (id_subcategory)
    );

    alter table tb_category 
       add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);

    alter table tb_subcategory 
       add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);

    alter table tb_lancamento 
       add constraint FKinndpk7lgvgdtwm7afpy8v4po 
       foreign key (id_subcategoria) 
       references tb_subcategory;

    alter table tb_subcategory 
       add constraint FKh8pmlxiiutxv9rqpmch0n46m2 
       foreign key (category_id) 
       references tb_category;

    create table tb_category (
       id_category  bigserial not null,
        nome varchar(255),
        primary key (id_category)
    );

    create table tb_lancamento (
       id_lancamento  bigserial not null,
        comentario varchar(255),
        data date,
        valor float8,
        id_subcategoria int8 not null,
        primary key (id_lancamento)
    );

    create table tb_subcategory (
       id_subcategory  bigserial not null,
        nome varchar(255),
        category_id int8,
        primary key (id_subcategory)
    );

    alter table tb_category 
       add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);

    alter table tb_subcategory 
       add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);

    alter table tb_lancamento 
       add constraint FKinndpk7lgvgdtwm7afpy8v4po 
       foreign key (id_subcategoria) 
       references tb_subcategory;

    alter table tb_subcategory 
       add constraint FKh8pmlxiiutxv9rqpmch0n46m2 
       foreign key (category_id) 
       references tb_category;

    create table tb_category (
       id_category  bigserial not null,
        nome varchar(255),
        primary key (id_category)
    );

    create table tb_lancamento (
       id_lancamento  bigserial not null,
        comentario varchar(255),
        data date,
        valor float8,
        id_subcategoria int8 not null,
        primary key (id_lancamento)
    );

    create table tb_subcategory (
       id_subcategory  bigserial not null,
        nome varchar(255),
        category_id int8,
        primary key (id_subcategory)
    );

    alter table tb_category 
       add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);

    alter table tb_subcategory 
       add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);

    alter table tb_lancamento 
       add constraint FKinndpk7lgvgdtwm7afpy8v4po 
       foreign key (id_subcategoria) 
       references tb_subcategory;

    alter table tb_subcategory 
       add constraint FKh8pmlxiiutxv9rqpmch0n46m2 
       foreign key (category_id) 
       references tb_category;

    create table tb_category (
       id_category  bigserial not null,
        nome varchar(255),
        primary key (id_category)
    );

    create table tb_lancamento (
       id_lancamento  bigserial not null,
        comentario varchar(255),
        data date,
        valor float8,
        id_subcategoria int8 not null,
        primary key (id_lancamento)
    );

    create table tb_subcategory (
       id_subcategory  bigserial not null,
        nome varchar(255),
        category_id int8,
        primary key (id_subcategory)
    );

    alter table tb_category 
       add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);

    alter table tb_subcategory 
       add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);

    alter table tb_lancamento 
       add constraint FKinndpk7lgvgdtwm7afpy8v4po 
       foreign key (id_subcategoria) 
       references tb_subcategory;

    alter table tb_subcategory 
       add constraint FKh8pmlxiiutxv9rqpmch0n46m2 
       foreign key (category_id) 
       references tb_category;

    create table tb_category (
       id_category  bigserial not null,
        nome varchar(255),
        primary key (id_category)
    );

    create table tb_lancamento (
       id_lancamento  bigserial not null,
        comentario varchar(255),
        data date,
        valor float8,
        id_subcategoria int8 not null,
        primary key (id_lancamento)
    );

    create table tb_subcategory (
       id_subcategory  bigserial not null,
        nome varchar(255),
        category_id int8,
        primary key (id_subcategory)
    );

    alter table tb_category 
       add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);

    alter table tb_subcategory 
       add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);

    alter table tb_lancamento 
       add constraint FKinndpk7lgvgdtwm7afpy8v4po 
       foreign key (id_subcategoria) 
       references tb_subcategory;

    alter table tb_subcategory 
       add constraint FKh8pmlxiiutxv9rqpmch0n46m2 
       foreign key (category_id) 
       references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
create table tb_category (id_category  bigserial not null, nome varchar(255), primary key (id_category));
create table tb_lancamento (id_lancamento  bigserial not null, comentario varchar(255), data date, valor float8, id_subcategoria int8 not null, primary key (id_lancamento));
create table tb_subcategory (id_subcategory  bigserial not null, nome varchar(255), category_id int8, primary key (id_subcategory));
alter table tb_category add constraint UK_322qhdid040fnhy83od1ep47t unique (nome);
alter table tb_subcategory add constraint UK_2dpsx0xd300qsyflbm7u0vxtb unique (nome);
alter table tb_lancamento add constraint FKinndpk7lgvgdtwm7afpy8v4po foreign key (id_subcategoria) references tb_subcategory;
alter table tb_subcategory add constraint FKh8pmlxiiutxv9rqpmch0n46m2 foreign key (category_id) references tb_category;
